/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StockRouteImport } from './routes/stock'
import { Route as MasterDataRouteImport } from './routes/master-data'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UnitsIndexRouteImport } from './routes/units/index'
import { Route as SuppliersIndexRouteImport } from './routes/suppliers/index'
import { Route as MaterialsIndexRouteImport } from './routes/materials/index'
import { Route as UnitsIdRouteImport } from './routes/units/$id'
import { Route as SuppliersIdRouteImport } from './routes/suppliers/$id'
import { Route as MaterialsOutboundRouteImport } from './routes/materials/outbound'
import { Route as MaterialsNewRouteImport } from './routes/materials/new'
import { Route as MaterialsInboundRouteImport } from './routes/materials/inbound'
import { Route as MaterialsIdRouteImport } from './routes/materials/$id'

const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterDataRoute = MasterDataRouteImport.update({
  id: '/master-data',
  path: '/master-data',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnitsIndexRoute = UnitsIndexRouteImport.update({
  id: '/units/',
  path: '/units/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersIndexRoute = SuppliersIndexRouteImport.update({
  id: '/suppliers/',
  path: '/suppliers/',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsIndexRoute = MaterialsIndexRouteImport.update({
  id: '/materials/',
  path: '/materials/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnitsIdRoute = UnitsIdRouteImport.update({
  id: '/units/$id',
  path: '/units/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersIdRoute = SuppliersIdRouteImport.update({
  id: '/suppliers/$id',
  path: '/suppliers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsOutboundRoute = MaterialsOutboundRouteImport.update({
  id: '/materials/outbound',
  path: '/materials/outbound',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsNewRoute = MaterialsNewRouteImport.update({
  id: '/materials/new',
  path: '/materials/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsInboundRoute = MaterialsInboundRouteImport.update({
  id: '/materials/inbound',
  path: '/materials/inbound',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsIdRoute = MaterialsIdRouteImport.update({
  id: '/materials/$id',
  path: '/materials/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/master-data': typeof MasterDataRoute
  '/stock': typeof StockRoute
  '/materials/$id': typeof MaterialsIdRoute
  '/materials/inbound': typeof MaterialsInboundRoute
  '/materials/new': typeof MaterialsNewRoute
  '/materials/outbound': typeof MaterialsOutboundRoute
  '/suppliers/$id': typeof SuppliersIdRoute
  '/units/$id': typeof UnitsIdRoute
  '/materials/': typeof MaterialsIndexRoute
  '/suppliers/': typeof SuppliersIndexRoute
  '/units/': typeof UnitsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/master-data': typeof MasterDataRoute
  '/stock': typeof StockRoute
  '/materials/$id': typeof MaterialsIdRoute
  '/materials/inbound': typeof MaterialsInboundRoute
  '/materials/new': typeof MaterialsNewRoute
  '/materials/outbound': typeof MaterialsOutboundRoute
  '/suppliers/$id': typeof SuppliersIdRoute
  '/units/$id': typeof UnitsIdRoute
  '/materials': typeof MaterialsIndexRoute
  '/suppliers': typeof SuppliersIndexRoute
  '/units': typeof UnitsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/master-data': typeof MasterDataRoute
  '/stock': typeof StockRoute
  '/materials/$id': typeof MaterialsIdRoute
  '/materials/inbound': typeof MaterialsInboundRoute
  '/materials/new': typeof MaterialsNewRoute
  '/materials/outbound': typeof MaterialsOutboundRoute
  '/suppliers/$id': typeof SuppliersIdRoute
  '/units/$id': typeof UnitsIdRoute
  '/materials/': typeof MaterialsIndexRoute
  '/suppliers/': typeof SuppliersIndexRoute
  '/units/': typeof UnitsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/master-data'
    | '/stock'
    | '/materials/$id'
    | '/materials/inbound'
    | '/materials/new'
    | '/materials/outbound'
    | '/suppliers/$id'
    | '/units/$id'
    | '/materials/'
    | '/suppliers/'
    | '/units/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/master-data'
    | '/stock'
    | '/materials/$id'
    | '/materials/inbound'
    | '/materials/new'
    | '/materials/outbound'
    | '/suppliers/$id'
    | '/units/$id'
    | '/materials'
    | '/suppliers'
    | '/units'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/master-data'
    | '/stock'
    | '/materials/$id'
    | '/materials/inbound'
    | '/materials/new'
    | '/materials/outbound'
    | '/suppliers/$id'
    | '/units/$id'
    | '/materials/'
    | '/suppliers/'
    | '/units/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  MasterDataRoute: typeof MasterDataRoute
  StockRoute: typeof StockRoute
  MaterialsIdRoute: typeof MaterialsIdRoute
  MaterialsInboundRoute: typeof MaterialsInboundRoute
  MaterialsNewRoute: typeof MaterialsNewRoute
  MaterialsOutboundRoute: typeof MaterialsOutboundRoute
  SuppliersIdRoute: typeof SuppliersIdRoute
  UnitsIdRoute: typeof UnitsIdRoute
  MaterialsIndexRoute: typeof MaterialsIndexRoute
  SuppliersIndexRoute: typeof SuppliersIndexRoute
  UnitsIndexRoute: typeof UnitsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-data': {
      id: '/master-data'
      path: '/master-data'
      fullPath: '/master-data'
      preLoaderRoute: typeof MasterDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/units/': {
      id: '/units/'
      path: '/units'
      fullPath: '/units/'
      preLoaderRoute: typeof UnitsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers/': {
      id: '/suppliers/'
      path: '/suppliers'
      fullPath: '/suppliers/'
      preLoaderRoute: typeof SuppliersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials/': {
      id: '/materials/'
      path: '/materials'
      fullPath: '/materials/'
      preLoaderRoute: typeof MaterialsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/units/$id': {
      id: '/units/$id'
      path: '/units/$id'
      fullPath: '/units/$id'
      preLoaderRoute: typeof UnitsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers/$id': {
      id: '/suppliers/$id'
      path: '/suppliers/$id'
      fullPath: '/suppliers/$id'
      preLoaderRoute: typeof SuppliersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials/outbound': {
      id: '/materials/outbound'
      path: '/materials/outbound'
      fullPath: '/materials/outbound'
      preLoaderRoute: typeof MaterialsOutboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials/new': {
      id: '/materials/new'
      path: '/materials/new'
      fullPath: '/materials/new'
      preLoaderRoute: typeof MaterialsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials/inbound': {
      id: '/materials/inbound'
      path: '/materials/inbound'
      fullPath: '/materials/inbound'
      preLoaderRoute: typeof MaterialsInboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials/$id': {
      id: '/materials/$id'
      path: '/materials/$id'
      fullPath: '/materials/$id'
      preLoaderRoute: typeof MaterialsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  MasterDataRoute: MasterDataRoute,
  StockRoute: StockRoute,
  MaterialsIdRoute: MaterialsIdRoute,
  MaterialsInboundRoute: MaterialsInboundRoute,
  MaterialsNewRoute: MaterialsNewRoute,
  MaterialsOutboundRoute: MaterialsOutboundRoute,
  SuppliersIdRoute: SuppliersIdRoute,
  UnitsIdRoute: UnitsIdRoute,
  MaterialsIndexRoute: MaterialsIndexRoute,
  SuppliersIndexRoute: SuppliersIndexRoute,
  UnitsIndexRoute: UnitsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
